language: java
jdk:
  - oraclejdk8

stages:
  - Build
  - "Release / Deploy"

env:
  global:
    - DEPLOY_REPO=MiguelMartinRojas/TaskanaSimpleHistory
  
jobs:
  include:
    - stage: Build
      script:
        - mvn clean install -q -f lib -DskipTests -Dmaven.javadoc.skip=true
    - stage: "Release / Deploy"
      script:
        - ci/release.sh lib/taskana-history-plugin $TRAVIS_TAG
      if: repo = env(DEPLOY_REPO) AND (tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ OR branch = TSK-657) AND type != pull_request
